Repository phamleduy04/hackutd24, pull requests merged in 2024-11, with the labels that each got.

#2 init backend and frontend
  .github/workflows/analysis.yml
  .github/workflows/eslint.yml
  .github/workflows/pr-review.yml
  .gitignore
  backend/eslint.config.mjs
  backend/jest.config.js
  backend/package.json
  backend/pnpm-lock.yaml
  backend/src/app.ts
  backend/src/routes/index.ts
  backend/src/server.ts
  backend/src/test/error.spec.ts
  backend/src/test/routes/index.spec.ts
  backend/tsconfig.json
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/postcss.config.js
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/components/Home.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/test/App.test.tsx
  frontend/src/test/components/Home.test.tsx
  frontend/src/vite-env.d.ts
  frontend/src/vitest.setup.ts
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  package.json
  pnpm-lock.yaml
Labels: size/XXL, Review effort [1-5]: 3

#5 Add API endpoints for file upload and listing with Pinata integration
  .gitignore
  backend/.env.example
  backend/.gitignore
  backend/package.json
  backend/pnpm-lock.yaml
  backend/src/app.ts
  backend/src/routes/api.ts
  backend/src/utils/pinata.ts
Labels: size/XL

#7 Initial frontend
  backend/package.json
  backend/pnpm-lock.yaml
  backend/src/app.ts
  frontend/components.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/components/AppLayout.tsx
  frontend/src/components/AppSidebar.tsx
  frontend/src/components/Home.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/scroll-area.tsx
  frontend/src/components/ui/separator.tsx
  frontend/src/components/ui/sheet.tsx
  frontend/src/components/ui/sidebar.tsx
  frontend/src/components/ui/skeleton.tsx
  frontend/src/components/ui/tooltip.tsx
  frontend/src/hooks/use-mobile.tsx
  frontend/src/index.css
  frontend/src/lib/requests.ts
  frontend/src/lib/utils.ts
  frontend/src/main.tsx
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: size/XXL

#8 Replace 'itemsLeftBehind' with 'description' in Home component
  frontend/src/App.tsx
  frontend/src/components/Home.tsx
  frontend/src/lib/requests.ts
Labels: size/S

#6 Enhance Pinata integration with public group support and file upload improvements
  backend/.env.example
  backend/baseline.jpg
  backend/package.json
  backend/pnpm-lock.yaml
  backend/src/aiPrompt/index.ts
  backend/src/app.ts
  backend/src/cli/createPublicGroup.ts
  backend/src/config/index.ts
  backend/src/routes/api.ts
  backend/src/utils/pinata.ts
  backend/test.jpg
Labels: size/L

#12 Ci pr review
  .github/workflows/pr-review.yml
  .gitignore
Labels: size/S, Review effort [1-5]: 2

#13 Terraform setup
  terraform/.gitignore
  terraform/README.md
  terraform/main.tf
Labels: size/M, Review effort [1-5]: 2

#4 feat: begin car-hub
  car-hub/.gitignore
  car-hub/Pipfile
  car-hub/Pipfile.lock
  car-hub/README.md
  car-hub/main.py
  test.txt
Labels: size/L

#15 docs: add link to onshape model
  3D_MODEL.md
Labels: size/XS, Review effort [1-5]: 1

#16 dockerize backend
  .github/workflows/docker-build.yml
  backend/.dockerignore
  backend/.gitignore
  backend/Dockerfile
  backend/docker-compose.yml
  backend/src/aiPrompt/index.ts
  backend/src/cli/createPublicGroup.ts
  backend/src/pinata/index.ts
  backend/src/pushNotification/index.ts
  backend/src/routes/api.ts
Labels: size/L

#17 Add DNS records for backend
  frontend/src/lib/requests.ts
  terraform/main.tf
Labels: size/S, Review effort [1-5]: 2

#18 Update title on FE
  frontend/src/components/Home.tsx
Labels: size/XS, Review effort [1-5]: 1

#19 Embedded
  embedded/.gitignore
  embedded/.vscode/extensions.json
  embedded/platformio.ini
  embedded/src/main.cpp
Labels: Review effort [1-5]: 3, size/L

#20 Dui
  .github/workflows/docker-build.yml
  backend/src/pinata/index.ts
  backend/src/routes/api.ts
Labels: size/XS

#21 no fetch on frontend
  .github/workflows/docker-build.yml
  .github/workflows/pr-review.yml
  .github/workflows/write-comment.yml
  frontend/src/lib/requests.ts
Labels: size/M, Review effort [1-5]: 2

#22 add images
  images/Graph how it work.excalidraw.png
  images/Hardware graph pt2.png
  images/Hardware graph.png
  images/Screenshot 2024-11-21 at 1.25.39 PM.png
  images/Screenshot 2024-11-21 at 1.25.55 PM.png
  images/Screenshot 2024-11-21 at 1.25.59 PM.png
  images/Screenshot 2024-11-21 at 1.46.49 PM.png
  images/Screenshot 2024-11-21 at 1.47.30 PM.png
  images/Screenshot 2024-11-21 at 1.47.58 PM.png
  images/gallery.jpg
Labels: size/XS

#24 Limit return img
  backend/src/pinata/index.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/Home.tsx
Labels: size/L
